import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Books from './Books'

export default function Home() {
  return (
    <div className='App'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Books />
      <Link href='/Add'>
        Add
      </Link>
      <Link href='/Update'>
        Update
      </Link>
    </div>
  )
}
